# Generated by Django 4.1 on 2022-09-05 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "token_name",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Authentication token name",
                    ),
                ),
                (
                    "token_secret",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        verbose_name="Authentication token secret",
                    ),
                ),
                (
                    "device_name",
                    models.TextField(blank=True, null=True, verbose_name="Device name"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Last used on",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
