# Generated by Django 4.1 on 2022-09-02 08:29

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoyaltyCard",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("store", models.CharField(max_length=512, verbose_name="Name")),
                ("note", models.TextField(verbose_name="Notes")),
                ("expiracy", models.DateField(verbose_name="Expires on")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Balance"
                    ),
                ),
                (
                    "balance_currency",
                    models.CharField(
                        help_text="Currency 3-letter symbol, ISO 4217",
                        max_length=3,
                        verbose_name="Balance currency",
                    ),
                ),
                ("card_id", models.TextField(verbose_name="Card ID")),
                (
                    "barcode_id_raw",
                    models.TextField(
                        blank=True,
                        help_text="Leave blank to reuse card ID",
                        null=True,
                        verbose_name="Barcode ID",
                    ),
                ),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("AZTEC", "Aztec"),
                            ("C39", "Code 39"),
                            ("C93", "Code 93"),
                            ("C128", "Code 128"),
                            ("CODABAR", "Codabar"),
                            ("DM", "Data Matrix"),
                            ("EAN8", "EAN 8"),
                            ("EAN13", "EAN 13"),
                            ("ITF", "ITF"),
                            ("PDF417", "PDF 417"),
                            ("QRCODE", "QR Code"),
                            ("UPCA", "UPC A"),
                            ("UPCE", "UPC E"),
                        ],
                        max_length=7,
                        verbose_name="Barcode type",
                    ),
                ),
                (
                    "header_color_raw",
                    models.PositiveIntegerField(
                        help_text="RGB color, 0xRRGGBB",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(16777215),
                        ],
                        verbose_name="Header color",
                    ),
                ),
                (
                    "star_status",
                    models.BooleanField(default=False, verbose_name="Starred"),
                ),
                (
                    "archive_status",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                ("last_used", models.DateTimeField(verbose_name="Last used")),
                ("zoom_level", models.PositiveIntegerField(verbose_name="Zoom level")),
                (
                    "revision_id",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Revision ID"
                    ),
                ),
            ],
        ),
    ]
