# Generated by Django 4.1 on 2022-09-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loyaltycard",
            name="balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Balance",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltycard",
            name="balance_currency",
            field=models.CharField(
                default="EUR",
                help_text="Currency 3-letter symbol, ISO 4217",
                max_length=3,
                verbose_name="Balance currency",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltycard",
            name="expiracy",
            field=models.DateField(blank=True, null=True, verbose_name="Expires on"),
        ),
        migrations.AlterField(
            model_name="loyaltycard",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last used"),
        ),
        migrations.AlterField(
            model_name="loyaltycard",
            name="zoom_level",
            field=models.PositiveIntegerField(default=0, verbose_name="Zoom level"),
        ),
    ]
