# Generated by Django 4.1 on 2022-09-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_loyaltycard_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loyaltycard",
            name="note",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
    ]
